### PR TITLE
Replace UIWebView with WKWebView [#170705251]

### PR DESCRIPTION
**Pull request by ChadDowJ**

### CODE REVIEW

**Review by demosten — CHANGES_REQUESTED** [review]
@ChadDowJ I see your idea here. Can you confirm that you've tested your changes carefully. How did you test them?

**Comment by ChadDowJ** [comment]
@demosten Currently I have tested for changes inside of the test app inside of SwiftR. Everything seems to be fine there, but I can look to see if additional tests inside of Gekko can be done

**Comment by ChadDowJ** [comment]
@demosten After testing in the Gekko Test App it does seem like I need to make some changes to Gekko Demo App ViewController and Gekko SignalRSwiftRConnection (mainly removing the useWKWebView flag)

**Review by demosten — APPROVED** [review]
@ChadDowJ this is trickier than it looks. Anyway I will approve that with special opinion. When you make a bump PR for it please randomize but also assign me + QA. We need to make sure that bluegrass works

**Pull request merged**
